version: "3.9"

services:
  laramie-interface-webapi:
    #container_name: laramie-interface-webapi
    image: laramie-interface-webapi:v1
    build:
      dockerfile: 'Dockerfile'

    command: "npm run start-prod"

    volumes:
      - .:/apps
      - /app/node_modules
      - laramie-data_files:/var/lib/laramie-repository

    ports:
      - "3102:3102"

volumes:
  laramie-data_files:
    external: true

networks: 
  default:
    name: laramie
    driver: bridge
    external: true
