version: "3.9"

services:
  laramie-importacion-webapi:
    #container_name: laramie-importacion-webapi
    image: laramie-importacion-webapi:v1
    build:
      dockerfile: 'Dockerfile'
      network: host
    command: "npm run start-prod"

    volumes:
      - .:/app
      - /app/node_modules
      - laramie-data_files:/var/lib/laramie-repository

    ports:
      - "3072:3072"

volumes:
  laramie-data_files:
    external: true

networks: 
  default:
    name: laramie
    external: true
    driver: bridge
