version: "3.9"

services:
  major-laramie-seguridad-apigateway:
    #container_name: major-laramie-seguridad-apigateway
    image: major-laramie-seguridad-apigateway:v1
    build:
      dockerfile: 'Dockerfile'
    command: "npm run start-prod"

    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - "3001:3001"

networks: 
  default: 
    name: major-laramie