version: "3.9"

services:
  laramie-wav-webapi:
    #container_name: laramie-wav-webapi
    image: laramie-wav-webapi:v1
    build:
      dockerfile: 'Dockerfile'

    command: "npm run start-prod"

    volumes:
      - .:/app
      - /app/node_modules
      - laramie-data_files:/var/lib/laramie-repository

    ports:
      - "3092:3092"

volumes:
  laramie-data_files:
    external: true

networks: 
  default:
    name: laramie
    driver: bridge
    external: true
