version: "3.9"

services:
  major-laramie-contaduria-webapi:
    #container_name: major-laramie-contaduria-webapi
    image: major-laramie-contaduria-webapi:v1
    build:
      dockerfile: 'Dockerfile'
    command: "npm run start-prod"

    volumes:
      - .:/app
      - /app/node_modules
      - major-laramie-data_files:/var/lib/major-laramie-repository

    ports:
      - "3032:3032"

volumes:
  major-laramie-data_files:
    external: true

networks: 
  default:
    name: major-laramie
    driver: bridge