version: "3.9"

services:
  laramie-tesoreria-apigateway:
    #container_name: laramie-tesoreria-apigateway
    image: laramie-tesoreria-apigateway:v1
    build:
      dockerfile: 'Dockerfile'
    command: "npm run start-prod"

    volumes:
      - .:/app
      - /app/node_modules
      - laramie-data_files:/var/lib/laramie-repository

    ports:
      - "3041:3041"

volumes:
  laramie-data_files:
    external: true

networks: 
  default: 
    name: laramie
    external: true